### ISSUE TITLE
vsgmeshshader fails with "failed to create logical device."

### ISSUE THREAD

**Issue by loopless** [vsg-dev/vsgExamples#102]
Other vsg examples such as vsgdraw run fine, but vsgmeshshader fails at the line below with
"Error: vsg::Device::create(...) failed to create logical device."
Perhaps this support is lacking in the driver, but I would have expected the example to catch that earlier.

Windows 10, nVidia P2000, latest vulkan 1.2 drivers

`        auto mesh_features = window->getOrCreatePhysicalDevice()->getFeatures<VkPhysicalDeviceMeshShaderFeaturesNV, VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MESH_SHADER_FEATURES_NV>();
`

**Comment by robertosfield** [comment]
On Mon, 9 Aug 2021 at 17:50, loopless ***@***.***> wrote:

> Other vsg examples such as vsgdraw run fine, but vsgmeshshader fails at
> the line below with
> "Error: vsg::Device::create(...) failed to create logical device."
> Perhaps this support is lacking in the driver, but I would have expected
> the example to catch that earlier.
>
> Windows 10, nVidia P2000, latest vulkan 1.2 drivers
>
> auto mesh_features =
> window->getOrCreatePhysicalDevice()->getFeatures<VkPhysicalDeviceMeshShaderFeaturesNV,
> VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MESH_SHADER_FEATURES_NV>();
>
It's the hardware not the driver that is the issue with your system.  Mesh
shaders are only supported on more recent NVidia hardware -

The failure mechanism you are seeing is exactly what is expected - you set
up the features you need then ask the VSG/Vulkan to return a physical
device with those features, if they aren't supported the VSG will throw an
exception and your application should catch those and then decide what to
do next.

Cheers,
Robert.

**Comment by loopless** [comment]
Then I am not clear on why the error handling lines below are present if the expected behaviour is to throw an exception? So the code should both catch the exception and check for the features being returned as true to decide if mesh rendering is supported.

`
        std::cout<<"nv_features.meshShader = "<<mesh_features.meshShader<<std::endl;
        std::cout<<"nv_features.taskShader = "<<mesh_features.taskShader<<std::endl;

        if (!mesh_features.meshShader || !mesh_features.taskShader)
        {
            std::cout<<"Mesh shaders not supported."<<std::endl;
            return 1;
        }
`

**Comment by robertosfield** [comment]
In Vulkan you have physical (vkPhyscialDevice/vsg::PhyscialDevice) and logical devices (vkDevice/vsg::Device).  You render using the logical device, but each logical device is created from a physical device.  

First you attempt to crater the physical device that fits your feature requirements, if one isn't available then the create physical device will fail and throw an exception.  If this succeeds then you can request a logical device with the specific feature you need enabled.

I forgot, Vulkan also has the vkInstance/vsg::Instance that you also need to create first to give you a connection with the driver in order to attempt to create the physical device.  This also needs to be created with extensions you'll need.

This complexity the VSG attempts to hide for normal usage, but if you are using advanced extensions like mesh shaders then checking all the required facilities requires one to learn about all these elements.
