### ISSUE TITLE
What's mean about "event not handled, response_type = 35"

### ISSUE THREAD

**Issue by ChenKe404** [vsg-dev/vsgExamples#152]
When I run the example "vsgdraw", the console keeps printing this message.

**Comment by ChenKe404** [comment]
![2022-06-01-13-11-29](https://user-images.githubusercontent.com/75658944/171334060-ce239991-8334-4f69-9c87-fea65fb2bc83.gif)
When I changed the window size of the example "vsgcameras", the size of the secondary_view became abnormal. 
Is this because the class "ViewportState" uses an inexact uint32_t type?

**Comment by robertosfield** [comment]
I don't see these issues on my Kubuntu 21.10 + AMD 5700G system.  Now
console warnings and no major problems with the viewport sizing.

What OS variant and version are you using?

What hardware + drivers?

Which version of Vulkan/VulkanSDK are you using?

How recent is the version of the VSG and vsgExamples are you using?

The event not handled warning looks to be a Xcb (from my
/usr/include/Xcb/xproto.h):

/** Opcode for xcb_ge_generic. */
#define XCB_GE_GENERIC 35

/**
 * @brief xcb_ge_generic_event_t
 **/
typedef struct xcb_ge_generic_event_t {
    uint8_t  response_type;
    uint8_t  extension;
    uint16_t sequence;
    uint32_t length;
    uint16_t event_type;
    uint8_t  pad0[22];
    uint32_t full_sequence;
} xcb_ge_generic_event_t;


Recent versions of VulkanSceneGraph/src/vsg/platform/unix/Xcb_Window.cpp
handle this, but as there is no docs for it there is no way to know what
should be done with it.  The code in the Xcb_Window.cpp is:

        case (XCB_GE_GENERIC):
        {
            // can't find meaningful documentation on what information is
encoded in a xcb_ge_generic_event_t
            // so no way to map it to anything on the VSG side.
            //
            // auto generic_event = reinterpret_cast<const
xcb_ge_generic_event_t*>(event);
            // std::cout<<"generic_event->event_type =
"<<generic_event->event_type<<std::endl;
            break;
        }

Since this should be ignoring the 35 event my best guess is you are using
an out of date VSG version and really should update to VG and vsgExamples
master and retest.

**Comment by ChenKe404** [comment]
Hi,Robert.
Thanks for your reply,these are my environments info:
GPU: Radeon RX Vega 8 Processor Graphics
Dirver: AMD Open Source Driver for Vulkan (amdvlk - version 2022.Q1.3)
OS: LinuxLite5.6 (based on Ubuntu20.04)
VSG version 0.2.11 (in CMakeLists.txt)
Example version latest
Vulkan version 1.3.204

By the way,the "event not handled, response_type = 35" message only printing when the window is resized.

**Comment by robertosfield** [comment]
On Wed, 1 Jun 2022 at 07:51, ChenKe ***@***.***> wrote:

> Hi,Robert.
> Thanks for your reply,these are my environments info:
> GPU: Radeon RX Vega 8 Processor Graphics
> Dirver: AMD Open Source Driver for Vulkan (amdvlk - version 2022.Q1.3)
> OS: LinuxLite5.6 (based on Ubuntu20.04)
> VSG version 0.2.11 (in CMakeLists.txt)
> Example version latest
> Vulkan version 1.3.204
>
> By the way,the "event not handled, response_type = 35" message only
> printing when the window is resized.
>
You definitely should update the VSG, vsgXchange, and vsgExamples and any
other VSG projects that you have.

**Comment by robertosfield** [comment]
I can't reproduce the extreme issues you are seeing, but it looks like this
might be because the minimum window size is constrained by my window
manager.

What Window Manager are you using?  Is the window size going to zero or
close to zero height?

If you really want users to be able to do this then you'll need to
implement a custom resize handler for this usage case, or just set a
minimum window size so the ratios of the viewports doesn't end up crazy.

**Comment by ChenKe404** [comment]
My desktop is xfce4 and window manager is xfwm4.
When i changed the window size, the size ratio and margin of the secondary_view may be different from the starting value.
For example, if I set the margin value of secondary_view to 10, the margin value may become 5 or less after changing the window size.This can also happen with the size of the secondary_view.
Although the width and height of the window won't necessarily be zero, I think this kind of problem might also arise in some cases.

Sorry I've tried to express my meaning in English as much as possible.
