### ISSUE TITLE
Nonsens output instead of graphics display on the Mac

### ISSUE THREAD

**Issue by rainergericke** [vsg-dev/vsgExamples#159]
Beginning with the last commits (GDAL integration into vsgXchange etc.) some examples are broken on the Mac.
It is:
vsgdraw
vsgexecutecommands
vsginterleaved
vsgmultigpu

These examples generate a huge amount of data and put it into stderr. It is binary data. With
vsgdraw -d
I tried to get a human readable message. You can see it in the attached image.
<img width="1476" alt="Bildschirmfoto 2022-07-02 um 09 47 52" src="https://user-images.githubusercontent.com/31243285/176992069-6f673aef-46b6-4beb-866e-b5e555a67ede.png">

**Comment by rainergericke** [comment]
Sorry I sent the wrong image.
<img width="1479" alt="Bildschirmfoto 2022-07-02 um 09 50 00" src="https://user-images.githubusercontent.com/31243285/176992127-3e9d5d85-f227-4c69-8f7b-fec6b10622d6.png">

**Comment by rainergericke** [comment]
Addition: same occurs on Windows.

**Comment by robertosfield** [comment]
Arrggh... I'm see that too with vsgdraw, in my testing I didn't attempt to run these examples.

When I've seen errors like this before it's been due to reading of old VSG files that the new serializers don't recognize.  As i've just removed all the deprecated serializer code paths in prep for 1.0 this would be my suspicion, see this thread for discussion of the changes: 

    [SerializationCleanUp and DeprecatedSerialization](https://groups.google.com/g/vsg-users/c/ireVYU-rMh8)

I am investigating.

**Comment by robertosfield** [comment]
Looks like I missed updating the vsgExamples/data/textures/lz.vsgb file, it's a really old file.  

Could you pull vsgExamples master to get the update lz.vsgb.

**Comment by rainergericke** [comment]
Thanks. The examples work again as expected!

**Comment by robertosfield** [comment]
That's a relief.  Thanks for testing.
