### ISSUE TITLE
data/ is not installed

### ISSUE THREAD

**Issue by fcami** [vsg-dev/vsgExamples#187]
The "make install" routine installs all binaries to a system, but does not seem to install the contents of the data/ directory which is needed for most examples to work. If these are redistributable in the same way (license) as the examples themselves, they should be installed too.

**Comment by robertosfield** [comment]
The data is under the same license.  The right thing to do is to install the data if you want to install.  Thought if we install the data does that also mean we have to encode paths to the data?  Otherwise developers still need to set VSG_FILE_PATH to the installed directory.

However, vsgExamples are examples, they aren't applications that would be normal to install.  Personally, I don't install the examples, or would recommend not installing, instead they should just be a used as a teaching material.

Another possibility would be to not have a install target, thus avoid the tangled web that it can cause.

Also, worth noting that while vsgExamples is going to 1.0.0 I don't view this repo as one that's appropriate for package maintainers to  wrap up and provide.

**Comment by fcami** [comment]
I agree with you that from a VSG developer's point of view, packaging vsgExamples has no value.

However, there is a good reason for distributions to provide this particular repo: testing. If examples work, package maintainers and in general distribution users can easily check whether a VSG update works well. 
Also, since VSG's behavior could arguably expose bugs in specific Vulkan implementations, there is still value in packaging vsgExamples. As long as this redistribution is done according to the terms of the license, of course. 

... and I was only pointing out a discrepancy in the "make install" routine here ;)

**Comment by robertosfield** [comment]
I have added an install target for data that places it in share/vsgExamples/data and checked it into vsgExamples master.

Appreciate some testing it by 3rd parties before I merge with vsgExamples-1.0 branch.

**Comment by fcami** [comment]
Thanks, much appreciated. Tested with:
```
$ VSG_FILE_PATH=/usr/share/vsgExamples/data/ vsgviewer models/teapot.vsgt
$ vsgviewer /usr/share/vsgExamples/data/models/teapot.vsgt
```
Both invocations work.

**Comment by robertosfield** [comment]
Thanks for the testing will merge with vsgExamples,. then later with 1.0 branch,

**Comment by robertosfield** [comment]
Already merged with vsgExamples master...
