### ISSUE TITLE
Findvsg.cmake not exists

### ISSUE THREAD

**Issue by remoe** [vsg-dev/vsgExamples#26]
This project need a Findvsg.cmake:

https://github.com/vsg-dev/vsgExamples/blob/master/CMakeLists.txt#L18

**Comment by vsg-dev** [comment]
The VSG installs the cmake configuration file along with the that cmake can find all the settings it needs from this config file.  It's the way that CMake team bow recommend over using a dedicated find script.  When running cmake in vsgExamples you should just need to set a VSG_DIR to the place you have installed the VSG.  If you have installed to system directories then even this should not be required.

**Comment by remoe** [comment]
Thanks, but this works only when one set this (CMake 3.15.2):

```-Dvsg_DIR:PATH=<vsg_install_path>/lib/cmake/vsg```

I never install on system path.

**Comment by vsg-dev** [comment]
I don't install to system paths either, I just use vsg_DIR to set the path.  You should be able to use vsg_DIR env path.

The approach we've taken we config installation follows the modern cmake recommendations.  There is an excellent video on youtube about this approach:

https://www.youtube.com/watch?v=bsXLMQ6WgIk&t=7s

**Comment by remoe** [comment]
Yes, it works with an Env var "vsg_DIR" but not with "-Dvsg_Dir ...". I never had such issues with Find<package>.cmake. Normally one don't need any environment variable if one correctly use:

```CMAKE_FIND_ROOT_PATH``` and ```CMAKE_PREFIX_PATH```

**Comment by OpenSiege** [comment]
I agree with Robert on this. Supporting deprecated CMake isn't optimal and should be avoided as much as possible. What platform are you building on? I don't have to set my environmental variables at all.

**Comment by remoe** [comment]
@OpenSiege  FindPackage is not deprecated. I've build with windows x64  (VS2017) and CMake 3.15.2.

**Comment by vsg-dev** [comment]
The CMake package config scheme works with findpackage, but instead of you needing a findvsg.cmake the configuration is all placed in the lib directory.  It's a far better scheme as you can have multiple installs all with different settings that you should build with and those settings are picked up from the install config file.  It's really powerful so I recommend you learn about it.

I have done some experiments on my system and by putting the install location on my PATH env variable CMake is able to pick up the install location and all the libs and settings required.

This is the approach I use, install locally built libs into my home directories Install directory.

When building the VSG I set the install path via :

  cmake -DCMAKE_INSTALL_PREFIX=~/Install
  make -j 16
  make install

To my env var I also set the PATH to pick up on installed binaries:

   export PATH=~/Install:${PATH}

Then when I do any builds cmake finds the VSG, osg2vsg etc. simply for the PATH variable.

If I don't set this, or install into system directories, then I can use vsg_DIR to set the path i.e.

  cmake . -Dvsg_DIR=~/Install

I will have think about adding further notes the INSTALL.md on this topic.

**Comment by remoe** [comment]
@vsg-dev ok. I use CMAKE_INSTALL_PREFIX to install any library of a specific version to a specific folder like "vsg-master" or "vsg-1.0.0" as well. All libraries are on a platform specific sub-folder. Then one can use ```CMAKE_FIND_ROOT_PATH``` to set a root SDK folder for all libraries. Then one can use ```CMAKE_PREFIX_PATH``` to set all used libraries: -DMAKE_PREFIX_PATH=/a-3.6.2;/b-7.58.0;/c-3.5.2;/d-4.0.9;...". Then CMake should find all this specific versions. I build ~60 libraries/frameworks on four (windows,macosx,linux,wasm) different platforms and it works very well.

**Comment by robertosfield** [comment]
On Mon, 2 Sep 2019 at 11:10, Remo E <notifications@github.com> wrote:

> @vsg-dev <https://github.com/vsg-dev> ok. I use CMAKE_INSTALL_PREFIX to
> install any library of a specific version to a specific folder like
> "vsg-master" or "vsg-1.0.0" as well. All libraries are on a platform
> specific sub-folder. Then one can use CMAKE_FIND_ROOT_PATH to set a root
> SDK folder for all libraries. Then one can use CMAKE_PREFIX_PATH to set
> all used libraries:
> -DMAKE_PREFIX_PATH=/a-3.6.2;/b-7.58.0;/c-3.5.2;/d-4.0.9;...". Then CMake
> should find all this specific versions. I build ~60 libraries/frameworks on
> four (windows,macosx,linux,wasm) different platforms and it works very well.
>
We are using the approach that the CMake team recommend, so if it doesn't
work for your particular approach then there might be something amiss with
our config or perhaps there is something missing with CMake, or the scheme
you are using isn't a robust as it could.

Please bare in mind, the VSG won't be alone in adopt config support, it's a
better approach that supplying find*.cmake scripts and is the now recommend
by CMake team, so getting your build to work with the VSG will make it more
future proof.

So I can try and recreate your usage approach, do you mean
-DCMAKE_PREFIX_PATH rather than -DMAKE_PREFIX?

**Comment by remoe** [comment]
yes ```CMAKE_PREFIX_PATH```

**Comment by remoe** [comment]
@robertosfield, sorry, I found my approach works only with SDK's, but it doesn't really work with "out-of-tree" projects.
