### ISSUE TITLE
problem with overlay views using multiple render graphs in the same window

### ISSUE THREAD

**Issue by theodoregoetz** [vsg-dev/vsgExamples#310]
In PR #309 I tried to split up the multiviews example into separate render graphs. The problem this example shows is that the secondary rendergraph clears the whole screen instead of it's designated smaller render area and I'm not sure how to get it working like the multiviews example.

Here is a screenshot for vsgmultirendergraphs:

![image](https://github.com/vsg-dev/vsgExamples/assets/3765682/53668f53-dca8-4d01-9619-a594f303b7c3)

This is expected (from vsgmultiviews):

![image](https://github.com/vsg-dev/vsgExamples/assets/3765682/c1e0f384-4f3f-41fd-b193-ccbf9edec9ee)

**Comment by robertosfield** [comment]
Run your example with the Vulkan Validation Layer on (WindowTraints::debugLayer set to true) to see if there are any errors reported.

**Comment by robertosfield** [comment]
As a general comment, this issue sounds with using RenderGraph/RenderPass to target a portion of window and failing is something we've hit up against before.  For what I recall some drivers/hardware do what you expect while others fail - it's a characteristic of Vulkan/driver rather than a bug on the VSG/application side.

For these reasons multiple views it's best to use multiple vsg::View within a single vsg::RenderGraph.

**Comment by robertosfield** [comment]
I've just looked up the github history for vsgmultiviews example - I originally wrote it with both a multiple RenderGraph code path and a multiple vsg::View within a single RenderGraph but had to remove the multiple RenderGraph codepath as it just wasn't reliable across platforms:

https://github.com/vsg-dev/vsgExamples/commit/5c19f16a60baf14abd136c8dfb1ef9636944393d
