### ISSUE TITLE
2D overly example

### ISSUE THREAD

**Issue by shujaatak** [vsg-dev/vsgExamples#63]
Is there any 2D overly example? I want to draw menus over a 3D scene.

**Comment by robertosfield** [comment]
> Is there any 2D overly example? I want to draw menus over a 3D scene.

We don't have one yet.

I haven't tried this usage case yet.  First thought is to take a similar
approach to the vsgrendertexture example and utilize a
CommanGraph+RenderGraph for the 3D scene and a CommandGraph+RenderGraph for
the 2D scene.  I guess one would also need to look at using a custom
RenderPass to have the two passes work together.

**Comment by shujaatak** [comment]
I will try the suggested approaches although, for me, it would be difficult to implement as I am new to VSG.  However, it would be highly useful to have one such example in vsgExamples.

By the way, I love VSG!

**Comment by shujaatak** [comment]
I got amazed when I saw your this [VulkanSceneGraph Database Pager developments](https://www.youtube.com/watch?v=nPPifoUHcO8) demo, I wonder from where I can download the **test database** so that I may run that demo on my machine.

**Comment by robertosfield** [comment]
On Mon, 7 Sep 2020 at 12:23, Shujaat Ali Khan <notifications@github.com>
wrote:

> I got amazed when I saw your this VulkanSceneGraph Database Pager
> developments <https://www.youtube.com/watch?v=nPPifoUHcO8> demo, I wonder
> from where I can download the *test database* so that I may run that demo
> on my machine.
>
The database isn't publicly available.

It would be nice to collect together high res DEM and Imagery that is
published under a fully open license so we can generate a paged database
that could be freely shared.  My focus isn't on this side, it's on
developing the software rather than creating demo databases etc.
